---
name: build Wheel
# yamllint disable rule:truthy
on: [push, workflow_dispatch]
# yamllint enable

jobs:
  build-whl:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    steps:
      - uses: actions/checkout@v4
      - name: build container
        run: docker compose build component-build-whl
      - name: build wasm
        run: docker compose up component-build-whl --exit-code-from component-build-whl
